*** Variables ***
${quota_management_l}               xpath://div[@class='q-stepper__header row items-stretch justify-between q-stepper__header--alternative-labels q-stepper__header--border']//div[5]
${new_quota_l}                      xpath://span[contains(text(),'New Quota')]
${actions_l}                        xpath://div[contains(text(),'Actions')]
${refresh_quota_period_toggle_l}    xpath://div[contains(text(),'Refresh quota periodically')]
${audience_l}                       xpath://div[contains(text(),'Audience')]
${audience_criteria_arrow_l}        xpath://i[normalize-space()='keyboard_arrow_up']
${add_button_l}                     xpath://i[normalize-space()='add']
${audience_criteria_text_l}         xpath://input[@type='text']
${audience_operand_text_l}          xpath:(//input[@type='text'])[2]
${audience_criteria_l}              xpath:(//input[@type='text'])[3]
${save_and_continue_but_l}          xpath://button[@class='q-btn q-btn-item non-selectable no-outline q-ml-sm float-right btn-saveAndContinue q-btn--outline q-btn--rectangle text-primary q-btn--actionable q-focusable q-hoverable q-btn--wrap']//span[@class='q-btn__wrapper col row q-anchor--skip']
${delete_creteria_but_l}            xpath:(//i[@role='img'])[2]
${invitation_l}                     xpath://div[@class='q-stepper__title'][normalize-space()='Invitation']
${other_pref_l}                     xpath:(//div[contains(text(),'Other Preferences')])[1]
${resend_toggle_l}                  xpath:(//div[@class='q-toggle__track'])[3]
${reminder_toggle_l}                xpath:(//div[@class='q-toggle__track'])[4]
${alternative_ch_l}                 xpath:(//div[@class='q-toggle__track'])[5]
${activate_l}                       xpath://div[@class='q-stepper__title'][normalize-space()='Activate']
${preview_start_but_l}              xpath://span[normalize-space()='Start']
${card_title_l}                     xpath://div[@class='alterna-cx-card-title']
${preview_close_l}                  xpath://span[@class='alterna-cx-card-close alterna-cx-trigger-close']
${activate_toggle_l}                xpath://div[@class='q-toggle__track']
${yes_but_l}                        xpath://span[contains(text(),'Yes')]
${user_inv_l}                       xpath://div[@class='vue-treeselect__multi-value']
${send_users_but_l}                 xpath://span[contains(text(),'Send to Test Users')]
${save_l}                           xpath://span[contains(text(),'Save')]