*** Variables ***
${add_widget_l}     //span[normalize-space()='Add Widget']
${ai_xy_bubble_widget_l}        //div[contains(text(),'AI-XY & Bubble')]
${text_bubble_widget_l}     //img[@src='/statics/images/widgets/TextAnalyticsBubbleChart2.png']
${widget_title_l}       (//input[@type='text'])[3]
${data_type_l}      (//input[@type='text'])[5]
${layout_type1_l}        //div[contains(text(),'1 by 1 Display')]
${layout_type2_l}        //div[contains(text(),'2 by 2 Display')]
${layout_type3_l}        //div[contains(text(),'3 by 2 Display')]
${topic_model_l}        (//*[name()='svg'][@class='vue-treeselect__control-arrow'])[5]
${topic_model2_l}        (//*[name()='svg'][@class='vue-treeselect__control-arrow'])[6]
${text_analytics_tab_l}     //div[@class='q-tab__label'][normalize-space()='Text Analytics']
${ai_chart_l}       //div[contains(text(),'AI-Chart')]
${emotion_toggle_l}     (//div[@class='q-toggle__inner relative-position non-selectable q-toggle__inner--falsy'])[1]
${impact_butterfly_l}       //img[@src='/statics/images/widgets/TextAnalyticsImpactButterflyChart.png']
${text_analytics_widget_l}      //div[@class='q-tab__label'][normalize-space()='Text Analytics']
${impact_type_l}        (//input[@type='text'])[6]
${column_bar_l}          //div[contains(text(),'Column & Bar')]
${nps_channel_perf_l}       (//img[@src='/statics/images/widgets/NpsChannelPerformanceChart.png'])[1]
${trans_chan_l}             (//input[@type='text'])[6]
${gauge_l}                  (//div[@class='q-item__section column text-center q-item__section--main justify-center'][normalize-space()='Gauge'])[1]
${nps_gauge_l}              //img[@src='/statics/images/widgets/NpsGaugeChart.png']
${line_l}                   (//div[contains(text(),'Line')])[1]
${nps_trend_l}              //img[@src='/statics/images/widgets/NpsTrendChart.png']
${category_type_l}          (//input[@type='text'])[6]
${table_l}                  //div[@class='q-item__section column text-center q-item__section--main justify-center'][normalize-space()='Table']
${oetx_l}                   (//img[@src='/statics/images/widgets/OetxRelatedNpsTable.png'])[1]
${survey_flow_l}             (//input[@type='text'])[6]
${question_l}               (//input[@type='text'])[7]
${nps_question_l}           (//input[@type='text'])[8]
