*** Variables ***
${add_widget_l}     //span[normalize-space()='Add Widget']
${ai_xy_bubble_widget_l}        //div[contains(text(),'AI-XY & Bubble')]
${text_bubble_widget_l}     //img[@src='/statics/images/widgets/TextAnalyticsBubbleChart2.png']
${widget_title_l}       (//div[@class='self-center full-width no-outline q-py-none acx-input'])[1]
${data_type_l}          (//*[name()='svg'][@class='vue-treeselect__control-arrow'])[4]
${layout_type1_l}        //div[contains(text(),'1 by 1 Display')]
${layout_type2_l}        //div[contains(text(),'2 by 2 Display')]
${layout_type3_l}        //div[contains(text(),'3 by 2 Display')]
${topic_model_l}        (//*[name()='svg'][@class='vue-treeselect__control-arrow'])[5]
${topic_model2_l}        (//*[name()='svg'][@class='vue-treeselect__control-arrow'])[6]
${text_analytics_tab_l}     //div[@class='q-tab__label'][normalize-space()='Text Analytics']
${ai_chart_l}       //div[contains(text(),'AI-Chart')]
${emotion_toggle_l}     (//div[@class='q-toggle__inner relative-position non-selectable q-toggle__inner--falsy'])[1]
${impact_butterfly_l}       //img[@src='/statics/images/widgets/TextAnalyticsImpactButterflyChart.png']
${text_analytics_widget_l}      //div[@class='q-tab__label'][normalize-space()='Text Analytics']
${impact_type_l}        (//input[@type='text'])[6]
${column_bar_l}          //div[contains(text(),'Column & Bar')]
${nps_channel_perf_l}       (//img[@src='/statics/images/widgets/NpsChannelPerformanceChart.png'])[1]
${trans_chan_l}             (//input[@type='text'])[6]
${gauge_l}                  (//div[@class='q-item__section column text-center q-item__section--main justify-center'][normalize-space()='Gauge'])[1]
${nps_gauge_l}              //img[@src='/statics/images/widgets/NpsGaugeChart.png']
${line_l}                   (//div[contains(text(),'Line')])[1]
${nps_trend_l}              //img[@src='/statics/images/widgets/NpsTrendChart.png']
${category_type_l}          (//input[@type='text'])[6]
${table_l}                  //div[@class='q-item__section column text-center q-item__section--main justify-center'][normalize-space()='Table']
${oetx_l}                   (//img[@src='/statics/images/widgets/OetxRelatedNpsTable.png'])[1]
${survey_flow_l}                    (//input[@type='text'])[6]
${question_l}                       (//input[@type='text'])[7]
${nps_question_l}                   (//input[@type='text'])[8]
${branch_sent_l}                    (//img[@src='/statics/images/widgets/BranchSentimentPerformanceTable.png'])[1]
${chn_hie_lvl_l}                    (//*[name()='svg'][@class='vue-treeselect__control-arrow'])[5]
${parent_chn_hie_lvl_l}             (//*[name()='svg'][@class='vue-treeselect__control-arrow'])[6]
${branch_topic_l}                   (//img[@src='/statics/images/widgets/BranchTopicPerformanceTable.png'])[1]
${branch_topic_model_l}             (//*[name()='svg'][@class='vue-treeselect__control-arrow'])[7]
${oetx_widget_l}                    (//img[@src='/statics/images/widgets/OetxRelatedTextAnalyticsTable.png'])[1]
${nps_impact_anlys_widget_l}        (//img[@src='/statics/images/widgets/TopImpactTable.png'])[1]
${nps_impact_anyls_l}               (//div[@class='vue-treeselect__multi-value'])[1]
${ai_table_l}                       (//div[contains(text(),'AI-Table')])[1]
${comm_high_l}                      //img[@src='/statics/images/widgets/CommentsHighlightChart.png']